const webSocketRequestEventsBase = {
  POD_CREATE: "pod:create",
  POD_LIST: "pod:list",
  POD_GET: "pod:get",
  POD_MOVE: "pod:move",
  POD_RENAME: "pod:rename",
  POD_SET_GOAL: "pod:set-goal",
  POD_SET_PROVIDER: "pod:set-provider",
  POD_SET_MODEL: "pod:set-model",
  POD_SET_THINKING_LEVEL: "pod:set-thinking-level",
  POD_SET_SCHEDULE: "pod:set-schedule",
  POD_SET_MEMORY_ENABLED: "pod:set-memory-enabled",
  POD_GET_MEMORY: "pod:get-memory",
  POD_CLEAR_MEMORY: "pod:clear-memory",
  POD_DELETE: "pod:delete",
  POD_CHAT_SEND: "pod:chat:send",
  POD_CHAT_ABORT: "pod:chat:abort",
  CONNECTION_CREATE: "connection:create",
  CONNECTION_LIST: "connection:list",
  CONNECTION_DELETE: "connection:delete",
  CONNECTION_UPDATE: "connection:update",
  CANVAS_PASTE: "canvas:paste",
  REPOSITORY_LIST: "repository:list",
  REPOSITORY_CREATE: "repository:create",
  REPOSITORY_NOTE_CREATE: "repository-note:create",
  REPOSITORY_NOTE_LIST: "repository-note:list",
  REPOSITORY_NOTE_UPDATE: "repository-note:update",
  REPOSITORY_NOTE_DELETE: "repository-note:delete",
  POD_BIND_REPOSITORY: "pod:bind-repository",
  POD_UNBIND_REPOSITORY: "pod:unbind-repository",
  REPOSITORY_DELETE: "repository:delete",
  REPOSITORY_GIT_CLONE: "repository:git:clone",
  REPOSITORY_CHECK_GIT: "repository:check-git",
  CANVAS_CREATE: "canvas:create",
  CANVAS_LIST: "canvas:list",
  CANVAS_RENAME: "canvas:rename",
  CANVAS_DELETE: "canvas:delete",
  CANVAS_SWITCH: "canvas:switch",
  CANVAS_REORDER: "canvas:reorder",
  CANVAS_SECURITY_UPDATE: "canvas:security:update",
  REPOSITORY_GET_LOCAL_BRANCHES: "repository:get-local-branches",
  REPOSITORY_CHECK_DIRTY: "repository:check-dirty",
  REPOSITORY_CHECKOUT_BRANCH: "repository:checkout-branch",
  REPOSITORY_DELETE_BRANCH: "repository:delete-branch",
  REPOSITORY_PULL_LATEST: "repository:pull-latest",
  REPOSITORY_SET_MEMORY_ENABLED: "repository:set-memory-enabled",
  REPOSITORY_GET_MEMORY: "repository:get-memory",
  REPOSITORY_CLEAR_MEMORY: "repository:clear-memory",
  CURSOR_MOVE: "cursor:move",
  MANAGED_MCP_REGISTRY_LIST: "managed-mcp:registry:list",
  MANAGED_MCP_REGISTRY_SAVE: "managed-mcp:registry:save",
  MANAGED_MCP_REGISTRY_DELETE: "managed-mcp:registry:delete",
  MANAGED_MCP_REGISTRY_TEST: "managed-mcp:registry:test",
  POD_MCP_AVAILABILITY_LIST: "pod:mcp-availability:list",
  POD_SET_MCP_SERVER_NAMES: "pod:set-mcp-server-names",
  CONFIG_GET: "config:get",
  CONFIG_UPDATE: "config:update",
  AUTH_BOOTSTRAP: "auth:bootstrap",
  AUTH_UNLOCK_WORKSPACE: "auth:unlock-workspace",
  AUTH_UNLOCK_CANVAS: "auth:unlock-canvas",
  AUTH_UPDATE_WORKSPACE_PASSWORD: "auth:update-workspace-password",
  INTEGRATION_APP_CREATE: "integration:app:create",
  INTEGRATION_APP_DELETE: "integration:app:delete",
  INTEGRATION_APP_LIST: "integration:app:list",
  INTEGRATION_APP_GET: "integration:app:get",
  INTEGRATION_APP_RESOURCES: "integration:app:resources",
  INTEGRATION_APP_RESOURCES_REFRESH: "integration:app:resources:refresh",
  POD_BIND_INTEGRATION: "pod:bind-integration",
  POD_UNBIND_INTEGRATION: "pod:unbind-integration",
  RUN_DELETE: "run:delete",
  RUN_LOAD_HISTORY: "run:load-history",
  RUN_LOAD_POD_MESSAGES: "run:load-pod-messages",
  PLUGIN_LIST: "plugin:list",
  PLUGIN_INSTALL: "plugin:install",
  PLUGIN_DELETE: "plugin:delete",
  PLUGIN_UPDATE: "plugin:update",
  PLUGIN_REORDER: "plugin:reorder",
  POD_SET_PLUGINS: "pod:set-plugins",
  BACKUP_TRIGGER: "backup:trigger",
  BACKUP_TEST_CONNECTION: "backup:test-connection",
  PROVIDER_LIST: "provider:list",
  OPENCODE_PROVIDER_LIST: "opencode:provider:list",
  OPENCODE_ALIASES_LIST: "opencode:aliases:list",
  OPENCODE_ALIASES_CREATE: "opencode:aliases:create",
  OPENCODE_ALIASES_UPDATE: "opencode:aliases:update",
  OPENCODE_ALIASES_DELETE: "opencode:aliases:delete",
  OPENCODE_ALIASES_REORDER: "opencode:aliases:reorder",
  OPENCODE_ALIASES_REFRESH_PRESETS: "opencode:aliases:refresh-presets",
  OPENCODE_SERVER_RESTART: "opencode:server:restart",
} as const;

export const WebSocketRequestEvents = webSocketRequestEventsBase as
  typeof webSocketRequestEventsBase & {
    readonly HEARTBEAT_PONG: "heartbeat:pong";
  };

Object.defineProperty(WebSocketRequestEvents, "HEARTBEAT_PONG", {
  value: "heartbeat:pong",
  enumerable: false,
});

export type WebSocketRequestEvent =
  | (typeof webSocketRequestEventsBase)[keyof typeof webSocketRequestEventsBase]
  | "heartbeat:pong";

const webSocketResponseEventsBase = {
  CONNECTION_READY: "connection:ready",
  POD_CREATED: "pod:created",
  POD_LIST_RESULT: "pod:list:result",
  POD_GET_RESULT: "pod:get:result",
  POD_MOVED: "pod:moved",
  POD_RENAMED: "pod:renamed",
  POD_GOAL_SET: "pod:goal:set",
  POD_PROVIDER_SET: "pod:provider:set",
  POD_MODEL_SET: "pod:model:set",
  POD_THINKING_LEVEL_SET: "pod:thinking-level:set",
  POD_SCHEDULE_SET: "pod:schedule:set",
  POD_MEMORY_ENABLED_SET: "pod:memory-enabled:set",
  POD_MEMORY_RESULT: "pod:memory:result",
  POD_MEMORY_CLEARED: "pod:memory:cleared",
  POD_DELETED: "pod:deleted",
  POD_CHAT_ABORTED: "pod:chat:aborted",
  POD_ERROR: "pod:error",
  CONNECTION_CREATED: "connection:created",
  CONNECTION_LIST_RESULT: "connection:list:result",
  CONNECTION_DELETED: "connection:deleted",
  CONNECTION_UPDATED: "connection:updated",
  WORKFLOW_TRIGGERED: "workflow:triggered",
  WORKFLOW_AUTO_TRIGGERED: "workflow:auto-triggered",
  WORKFLOW_COMPLETE: "workflow:complete",
  WORKFLOW_PENDING: "workflow:pending",
  WORKFLOW_SOURCES_MERGED: "workflow:sources-merged",
  WORKFLOW_BRANCH_TRIGGERED: "workflow:branch:triggered",
  WORKFLOW_DIRECT_TRIGGERED: "workflow:direct-triggered",
  WORKFLOW_QUEUED: "workflow:queued",
  WORKFLOW_QUEUE_PROCESSED: "workflow:queue-processed",
  CANVAS_PASTE_RESULT: "canvas:paste:result",
  REPOSITORY_LIST_RESULT: "repository:list:result",
  REPOSITORY_CREATED: "repository:created",
  REPOSITORY_NOTE_CREATED: "repository-note:created",
  REPOSITORY_NOTE_LIST_RESULT: "repository-note:list:result",
  REPOSITORY_NOTE_UPDATED: "repository-note:updated",
  REPOSITORY_NOTE_DELETED: "repository-note:deleted",
  POD_REPOSITORY_BOUND: "pod:repository:bound",
  POD_REPOSITORY_UNBOUND: "pod:repository:unbound",
  REPOSITORY_DELETED: "repository:deleted",
  REPOSITORY_GIT_CLONE_PROGRESS: "repository:git:clone:progress",
  REPOSITORY_GIT_CLONE_RESULT: "repository:git:clone:result",
  REPOSITORY_CHECK_GIT_RESULT: "repository:check-git:result",
  HEARTBEAT_PING: "heartbeat:ping",
  HEARTBEAT_PONG: "heartbeat:pong",
  SCHEDULE_FIRED: "schedule:fired",
  CANVAS_CREATED: "canvas:created",
  CANVAS_LIST_RESULT: "canvas:list:result",
  CANVAS_RENAMED: "canvas:renamed",
  CANVAS_DELETED: "canvas:deleted",
  CANVAS_SWITCHED: "canvas:switched",
  CANVAS_REORDERED: "canvas:reordered",
  CANVAS_SECURITY_UPDATED: "canvas:security:updated",
  REPOSITORY_LOCAL_BRANCHES_RESULT: "repository:local-branches:result",
  REPOSITORY_DIRTY_CHECK_RESULT: "repository:dirty-check:result",
  REPOSITORY_CHECKOUT_BRANCH_PROGRESS: "repository:checkout-branch:progress",
  REPOSITORY_BRANCH_CHECKED_OUT: "repository:branch:checked-out",
  REPOSITORY_BRANCH_CHANGED: "repository:branch:changed",
  REPOSITORY_BRANCH_DELETED: "repository:branch:deleted",
  REPOSITORY_PULL_LATEST_PROGRESS: "repository:pull-latest:progress",
  REPOSITORY_PULL_LATEST_RESULT: "repository:pull-latest:result",
  REPOSITORY_MEMORY_ENABLED_SET: "repository:memory-enabled:set",
  REPOSITORY_MEMORY_RESULT: "repository:memory:result",
  REPOSITORY_MEMORY_CLEARED: "repository:memory:cleared",
  CURSOR_MOVED: "cursor:moved",
  CURSOR_LEFT: "cursor:left",
  MANAGED_MCP_REGISTRY_LIST_RESULT: "managed-mcp:registry:list:result",
  MANAGED_MCP_REGISTRY_SAVED: "managed-mcp:registry:saved",
  MANAGED_MCP_REGISTRY_DELETED: "managed-mcp:registry:deleted",
  MANAGED_MCP_REGISTRY_UPDATED: "managed-mcp:registry:updated",
  MANAGED_MCP_REGISTRY_TEST_RESULT: "managed-mcp:registry:test:result",
  MANAGED_MCP_SURFACE_TARGETS_IGNORED: "managed-mcp:surface:targets-ignored",
  POD_MCP_AVAILABILITY_LIST_RESULT: "pod:mcp-availability:list:result",
  POD_MCP_SERVER_NAMES_UPDATED: "pod:mcp-server-names:updated",
  CONFIG_GET_RESULT: "config:get:result",
  CONFIG_UPDATED: "config:updated",
  AUTH_BOOTSTRAP_RESULT: "auth:bootstrap:result",
  AUTH_WORKSPACE_UNLOCK_RESULT: "auth:unlock-workspace:result",
  AUTH_CANVAS_UNLOCK_RESULT: "auth:unlock-canvas:result",
  AUTH_WORKSPACE_PASSWORD_UPDATED: "auth:update-workspace-password:result",
  AUTH_SESSION_RESET: "auth:session:reset",
  AUTH_CANVAS_ACCESS_RESET: "auth:canvas-access:reset",
  INTEGRATION_APP_CREATED: "integration:app:created",
  INTEGRATION_APP_DELETED: "integration:app:deleted",
  INTEGRATION_APP_LIST_RESULT: "integration:app:list:result",
  INTEGRATION_APP_GET_RESULT: "integration:app:get:result",
  INTEGRATION_APP_RESOURCES_RESULT: "integration:app:resources:result",
  INTEGRATION_APP_RESOURCES_REFRESHED: "integration:app:resources:refreshed",
  POD_INTEGRATION_BOUND: "pod:integration:bound",
  POD_INTEGRATION_UNBOUND: "pod:integration:unbound",
  INTEGRATION_CONNECTION_STATUS_CHANGED:
    "integration:connection:status:changed",
  RUN_CREATED: "run:created",
  RUN_STATUS_CHANGED: "run:status:changed",
  RUN_POD_STATUS_CHANGED: "run:pod:status:changed",
  RUN_MESSAGE: "run:message",
  RUN_GOAL_ROUND_DIVIDER: "run:goal-round-divider",
  RUN_CHAT_COMPLETE: "run:chat:complete",
  RUN_CHAT_TOOL_USE: "run:tool_use",
  RUN_CHAT_TOOL_RESULT: "run:tool_result",
  RUN_DELETED: "run:deleted",
  RUN_HISTORY_RESULT: "run:history:result",
  RUN_POD_MESSAGES_RESULT: "run:pod-messages:result",
  PLUGIN_LIST_RESULT: "plugin:list:result",
  PLUGIN_INSTALLED: "plugin:installed",
  PLUGIN_DELETED: "plugin:deleted",
  PLUGIN_UPDATED: "plugin:updated",
  PLUGIN_REORDERED: "plugin:reordered",
  POD_PLUGINS_SET: "pod:plugins:set",
  BACKUP_TRIGGER_RESULT: "backup:trigger:result",
  BACKUP_STARTED: "backup:started",
  BACKUP_COMPLETED: "backup:completed",
  BACKUP_FAILED: "backup:failed",
  BACKUP_TEST_CONNECTION_RESULT: "backup:test-connection:result",
  PROVIDER_LIST_RESULT: "provider:list:result",
  OPENCODE_PROVIDER_LIST_RESULT: "opencode:provider:list:result",
  OPENCODE_ALIASES_LIST_RESULT: "opencode:aliases:list:result",
  OPENCODE_ALIASES_CREATE_RESULT: "opencode:aliases:create:result",
  OPENCODE_ALIASES_UPDATE_RESULT: "opencode:aliases:update:result",
  OPENCODE_ALIASES_DELETE_RESULT: "opencode:aliases:delete:result",
  OPENCODE_ALIASES_REORDER_RESULT: "opencode:aliases:reorder:result",
  OPENCODE_ALIASES_REFRESH_PRESETS_RESULT:
    "opencode:aliases:refresh-presets:result",
  OPENCODE_ALIASES_UPDATED: "opencode:aliases:updated",
  OPENCODE_SERVER_RESTART_RESULT: "opencode:server:restart:result",
} as const;

export const WebSocketResponseEvents = webSocketResponseEventsBase as
  typeof webSocketResponseEventsBase & {
    readonly RUN_POD_MESSAGES_LOADED:
      typeof webSocketResponseEventsBase.RUN_POD_MESSAGES_RESULT;
  };

Object.defineProperty(WebSocketResponseEvents, "RUN_POD_MESSAGES_LOADED", {
  value: webSocketResponseEventsBase.RUN_POD_MESSAGES_RESULT,
  enumerable: false,
});

export type WebSocketResponseEvent =
  (typeof webSocketResponseEventsBase)[keyof typeof webSocketResponseEventsBase];
