export const WebSocketRequestEvents = {
  POD_CREATE: "pod:create",
  POD_LIST: "pod:list",
  POD_GET: "pod:get",
  POD_MOVE: "pod:move",
  POD_RENAME: "pod:rename",
  POD_SET_GOAL: "pod:set-goal",
  POD_SET_MODEL: "pod:set-model",
  POD_SET_THINKING_LEVEL: "pod:set-thinking-level",
  POD_SET_SCHEDULE: "pod:set-schedule",
  POD_DELETE: "pod:delete",
  POD_CHAT_SEND: "pod:chat:send",
  POD_CHAT_ABORT: "pod:chat:abort",
  CONNECTION_CREATE: "connection:create",
  CONNECTION_LIST: "connection:list",
  CONNECTION_DELETE: "connection:delete",
  CONNECTION_UPDATE: "connection:update",
  CANVAS_PASTE: "canvas:paste",
  REPOSITORY_LIST: "repository:list",
  REPOSITORY_CREATE: "repository:create",
  REPOSITORY_DELETE: "repository:delete",
  REPOSITORY_CHECK_GIT: "repository:check-git",
  REPOSITORY_GIT_CLONE: "repository:git:clone",
  REPOSITORY_GET_LOCAL_BRANCHES: "repository:get-local-branches",
  REPOSITORY_CHECK_DIRTY: "repository:check-dirty",
  REPOSITORY_CHECKOUT_BRANCH: "repository:checkout-branch",
  REPOSITORY_DELETE_BRANCH: "repository:delete-branch",
  REPOSITORY_PULL_LATEST: "repository:pull-latest",
  REPOSITORY_NOTE_CREATE: "repository-note:create",
  REPOSITORY_NOTE_LIST: "repository-note:list",
  REPOSITORY_NOTE_UPDATE: "repository-note:update",
  REPOSITORY_NOTE_DELETE: "repository-note:delete",
  POD_BIND_REPOSITORY: "pod:bind-repository",
  POD_UNBIND_REPOSITORY: "pod:unbind-repository",
  /** 查詢指定 Provider 的 MCP server 清單 */
  MCP_LIST: "mcp:list",
  /** 查詢 managed MCP registry 清單 */
  MANAGED_MCP_REGISTRY_LIST: "managed-mcp:registry:list",
  /** 儲存 managed MCP registry entry */
  MANAGED_MCP_REGISTRY_SAVE: "managed-mcp:registry:save",
  /** 刪除 managed MCP registry entry */
  MANAGED_MCP_REGISTRY_DELETE: "managed-mcp:registry:delete",
  /** 查詢指定 Pod 的 MCP availability 清單 */
  POD_MCP_AVAILABILITY_LIST: "pod:mcp-availability:list",
  /** 設定指定 Pod 的 MCP server 名稱清單 */
  POD_SET_MCP_SERVER_NAMES: "pod:set-mcp-server-names",
  CANVAS_CREATE: "canvas:create",
  CANVAS_LIST: "canvas:list",
  CANVAS_RENAME: "canvas:rename",
  CANVAS_DELETE: "canvas:delete",
  CANVAS_SWITCH: "canvas:switch",
  CANVAS_REORDER: "canvas:reorder",
  CANVAS_SECURITY_UPDATE: "canvas:security:update",
  CURSOR_MOVE: "cursor:move",
  HEARTBEAT_PONG: "heartbeat:pong",
  CONFIG_GET: "config:get",
  CONFIG_UPDATE: "config:update",
  AUTH_BOOTSTRAP: "auth:bootstrap",
  AUTH_UNLOCK_WORKSPACE: "auth:unlock-workspace",
  AUTH_UNLOCK_CANVAS: "auth:unlock-canvas",
  AUTH_UPDATE_WORKSPACE_PASSWORD: "auth:update-workspace-password",
  INTEGRATION_APP_CREATE: "integration:app:create",
  INTEGRATION_APP_DELETE: "integration:app:delete",
  INTEGRATION_APP_LIST: "integration:app:list",
  INTEGRATION_APP_RESOURCES_REFRESH: "integration:app:resources:refresh",
  POD_BIND_INTEGRATION: "pod:bind-integration",
  POD_UNBIND_INTEGRATION: "pod:unbind-integration",
  RUN_DELETE: "run:delete",
  RUN_LOAD_HISTORY: "run:load-history",
  RUN_LOAD_POD_MESSAGES: "run:load-pod-messages",
  PLUGIN_LIST: "plugin:list",
  POD_SET_PLUGINS: "pod:set-plugins",
  BACKUP_TEST_CONNECTION: "backup:test-connection",
  BACKUP_TRIGGER: "backup:trigger",
  /** 查詢可用 Provider 列表 */
  PROVIDER_LIST: "provider:list",
  /** 查詢 opencode provider 列表 */
  OPENCODE_PROVIDER_LIST: "opencode:provider:list",
  /** 查詢 opencode model 別稱列表 */
  OPENCODE_ALIASES_LIST: "opencode:aliases:list",
  /** 新增 opencode model 別稱 */
  OPENCODE_ALIASES_CREATE: "opencode:aliases:create",
  /** 更新 opencode model 別稱 */
  OPENCODE_ALIASES_UPDATE: "opencode:aliases:update",
  /** 刪除 opencode model 別稱 */
  OPENCODE_ALIASES_DELETE: "opencode:aliases:delete",
  /** 重排 opencode model 別稱順序 */
  OPENCODE_ALIASES_REORDER: "opencode:aliases:reorder",
} as const;

export type WebSocketRequestEvents =
  (typeof WebSocketRequestEvents)[keyof typeof WebSocketRequestEvents];

export const WebSocketResponseEvents = {
  CONNECTION_READY: "connection:ready",
  POD_CREATED: "pod:created",
  POD_LIST_RESULT: "pod:list:result",
  POD_GET_RESULT: "pod:get:result",
  POD_MOVED: "pod:moved",
  POD_RENAMED: "pod:renamed",
  POD_GOAL_SET: "pod:goal:set",
  POD_MODEL_SET: "pod:model:set",
  POD_THINKING_LEVEL_SET: "pod:thinking-level:set",
  POD_SCHEDULE_SET: "pod:schedule:set",
  POD_DELETED: "pod:deleted",
  POD_CHAT_ABORTED: "pod:chat:aborted",
  POD_ERROR: "pod:error",
  CONNECTION_CREATED: "connection:created",
  CONNECTION_LIST_RESULT: "connection:list:result",
  CONNECTION_DELETED: "connection:deleted",
  CONNECTION_UPDATED: "connection:updated",
  WORKFLOW_TRIGGERED: "workflow:triggered",
  WORKFLOW_COMPLETE: "workflow:complete",
  WORKFLOW_ERROR: "workflow:error",
  WORKFLOW_AUTO_TRIGGERED: "workflow:auto-triggered",
  WORKFLOW_PENDING: "workflow:pending",
  WORKFLOW_SOURCES_MERGED: "workflow:sources-merged",
  WORKFLOW_BRANCH_PENDING: "workflow:branch:pending",
  WORKFLOW_BRANCH_RESULT: "workflow:branch:result",
  WORKFLOW_BRANCH_ERROR: "workflow:branch:error",
  WORKFLOW_BRANCH_CLEAR: "workflow:branch:clear",
  WORKFLOW_BRANCH_TRIGGERED: "workflow:branch:triggered",
  WORKFLOW_DIRECT_TRIGGERED: "workflow:direct-triggered",
  WORKFLOW_DIRECT_WAITING: "workflow:direct-waiting",
  WORKFLOW_QUEUED: "workflow:queued",
  WORKFLOW_QUEUE_PROCESSED: "workflow:queue-processed",
  CANVAS_PASTE_RESULT: "canvas:paste:result",
  REPOSITORY_LIST_RESULT: "repository:list:result",
  REPOSITORY_CREATED: "repository:created",
  REPOSITORY_DELETED: "repository:deleted",
  REPOSITORY_CHECK_GIT_RESULT: "repository:check-git:result",
  REPOSITORY_GIT_CLONE_PROGRESS: "repository:git:clone:progress",
  REPOSITORY_GIT_CLONE_RESULT: "repository:git:clone:result",
  REPOSITORY_LOCAL_BRANCHES_RESULT: "repository:local-branches:result",
  REPOSITORY_DIRTY_CHECK_RESULT: "repository:dirty-check:result",
  REPOSITORY_CHECKOUT_BRANCH_PROGRESS: "repository:checkout-branch:progress",
  REPOSITORY_BRANCH_CHECKED_OUT: "repository:branch:checked-out",
  REPOSITORY_BRANCH_CHANGED: "repository:branch:changed",
  REPOSITORY_BRANCH_DELETED: "repository:branch:deleted",
  REPOSITORY_PULL_LATEST_PROGRESS: "repository:pull-latest:progress",
  REPOSITORY_PULL_LATEST_RESULT: "repository:pull-latest:result",
  REPOSITORY_NOTE_CREATED: "repository-note:created",
  REPOSITORY_NOTE_LIST_RESULT: "repository-note:list:result",
  REPOSITORY_NOTE_UPDATED: "repository-note:updated",
  REPOSITORY_NOTE_DELETED: "repository-note:deleted",
  POD_REPOSITORY_BOUND: "pod:repository:bound",
  POD_REPOSITORY_UNBOUND: "pod:repository:unbound",
  /** MCP server 清單查詢結果 */
  MCP_LIST_RESULT: "mcp:list:result",
  /** managed MCP registry 清單查詢結果 */
  MANAGED_MCP_REGISTRY_LIST_RESULT: "managed-mcp:registry:list:result",
  /** managed MCP registry entry 已儲存 */
  MANAGED_MCP_REGISTRY_SAVED: "managed-mcp:registry:saved",
  /** managed MCP registry entry 已刪除 */
  MANAGED_MCP_REGISTRY_DELETED: "managed-mcp:registry:deleted",
  /** managed MCP registry 已更新（broadcast） */
  MANAGED_MCP_REGISTRY_UPDATED: "managed-mcp:registry:updated",
  /** Pod MCP availability 清單查詢結果 */
  POD_MCP_AVAILABILITY_LIST_RESULT: "pod:mcp-availability:list:result",
  /** Pod 的 MCP server 名稱清單已更新 */
  POD_MCP_SERVER_NAMES_UPDATED: "pod:mcp-server-names:updated",
  SCHEDULE_FIRED: "schedule:fired",
  CANVAS_CREATED: "canvas:created",
  CANVAS_LIST_RESULT: "canvas:list:result",
  CANVAS_RENAMED: "canvas:renamed",
  CANVAS_DELETED: "canvas:deleted",
  CANVAS_SWITCHED: "canvas:switched",
  CANVAS_REORDERED: "canvas:reordered",
  CANVAS_SECURITY_UPDATED: "canvas:security:updated",
  HEARTBEAT_PING: "heartbeat:ping",
  CURSOR_MOVED: "cursor:moved",
  CURSOR_LEFT: "cursor:left",
  CONFIG_GET_RESULT: "config:get:result",
  CONFIG_UPDATED: "config:updated",
  AUTH_BOOTSTRAP_RESULT: "auth:bootstrap:result",
  AUTH_WORKSPACE_UNLOCK_RESULT: "auth:unlock-workspace:result",
  AUTH_CANVAS_UNLOCK_RESULT: "auth:unlock-canvas:result",
  AUTH_WORKSPACE_PASSWORD_UPDATED: "auth:update-workspace-password:result",
  AUTH_SESSION_RESET: "auth:session:reset",
  AUTH_CANVAS_ACCESS_RESET: "auth:canvas-access:reset",
  INTEGRATION_APP_CREATED: "integration:app:created",
  INTEGRATION_APP_DELETED: "integration:app:deleted",
  INTEGRATION_APP_LIST_RESULT: "integration:app:list:result",
  INTEGRATION_APP_RESOURCES_REFRESHED: "integration:app:resources:refreshed",
  POD_INTEGRATION_BOUND: "pod:integration:bound",
  POD_INTEGRATION_UNBOUND: "pod:integration:unbound",
  INTEGRATION_CONNECTION_STATUS_CHANGED:
    "integration:connection:status:changed",
  RUN_CREATED: "run:created",
  RUN_STATUS_CHANGED: "run:status:changed",
  RUN_POD_STATUS_CHANGED: "run:pod:status:changed",
  RUN_MESSAGE: "run:message",
  RUN_CHAT_COMPLETE: "run:chat:complete",
  RUN_DELETED: "run:deleted",
  RUN_HISTORY_RESULT: "run:history:result",
  RUN_POD_MESSAGES_RESULT: "run:pod-messages:result",
  RUN_TOOL_USE: "run:tool_use",
  RUN_TOOL_RESULT: "run:tool_result",
  PLUGIN_LIST_RESULT: "plugin:list:result",
  POD_PLUGINS_SET: "pod:plugins:set",
  BACKUP_TEST_CONNECTION_RESULT: "backup:test-connection:result",
  BACKUP_TRIGGER_RESULT: "backup:trigger:result",
  BACKUP_STARTED: "backup:started",
  BACKUP_COMPLETED: "backup:completed",
  BACKUP_FAILED: "backup:failed",
  /** Provider 列表查詢結果 */
  PROVIDER_LIST_RESULT: "provider:list:result",
  /** opencode provider 列表查詢結果 */
  OPENCODE_PROVIDER_LIST_RESULT: "opencode:provider:list:result",
  /** opencode model 別稱列表查詢結果 */
  OPENCODE_ALIASES_LIST_RESULT: "opencode:aliases:list:result",
  /** opencode model 別稱新增結果 */
  OPENCODE_ALIASES_CREATE_RESULT: "opencode:aliases:create:result",
  /** opencode model 別稱更新結果 */
  OPENCODE_ALIASES_UPDATE_RESULT: "opencode:aliases:update:result",
  /** opencode model 別稱刪除結果 */
  OPENCODE_ALIASES_DELETE_RESULT: "opencode:aliases:delete:result",
  /** opencode model 別稱重排結果 */
  OPENCODE_ALIASES_REORDER_RESULT: "opencode:aliases:reorder:result",
  /** opencode model 別稱已更新（push 事件） */
  OPENCODE_ALIASES_UPDATED: "opencode:aliases:updated",
} as const;

export type WebSocketResponseEvents =
  (typeof WebSocketResponseEvents)[keyof typeof WebSocketResponseEvents];
