import {
  WebSocketRequestEvents,
  WebSocketResponseEvents,
  podCreateSchema,
  podListSchema,
  podGetSchema,
  podMoveSchema,
  podRenameSchema,
  podSetGoalSchema,
  podSetProviderSchema,
  podSetModelSchema,
  podSetThinkingLevelSchema,
  podSetFastModeSchema,
  podSetScheduleSchema,
  podSetMemoryEnabledSchema,
  podGetMemorySchema,
  podClearMemorySchema,
  podDeleteSchema,
  podSetPluginsSchema,
} from "../../schemas";
import {
  handlePodCreate,
  handlePodList,
  handlePodGet,
  handlePodMove,
  handlePodRename,
  handlePodSetGoal,
  handlePodSetProvider,
  handlePodSetModel,
  handlePodSetThinkingLevel,
  handlePodSetFastMode,
  handlePodSetSchedule,
  handlePodSetMemoryEnabled,
  handlePodGetMemory,
  handlePodClearMemory,
  handlePodDelete,
  handlePodSetPlugins,
} from "../podHandlers.js";
import { createHandlerGroup } from "./createHandlerGroup.js";

export const podHandlerGroup = createHandlerGroup({
  name: "pod",
  handlers: [
    {
      event: WebSocketRequestEvents.POD_CREATE,
      handler: handlePodCreate,
      schema: podCreateSchema,
      responseEvent: WebSocketResponseEvents.POD_CREATED,
    },
    {
      event: WebSocketRequestEvents.POD_LIST,
      handler: handlePodList,
      schema: podListSchema,
      responseEvent: WebSocketResponseEvents.POD_LIST_RESULT,
    },
    {
      event: WebSocketRequestEvents.POD_GET,
      handler: handlePodGet,
      schema: podGetSchema,
      responseEvent: WebSocketResponseEvents.POD_GET_RESULT,
    },
    {
      event: WebSocketRequestEvents.POD_MOVE,
      handler: handlePodMove,
      schema: podMoveSchema,
      responseEvent: WebSocketResponseEvents.POD_MOVED,
    },
    {
      event: WebSocketRequestEvents.POD_RENAME,
      handler: handlePodRename,
      schema: podRenameSchema,
      responseEvent: WebSocketResponseEvents.POD_RENAMED,
    },
    {
      event: WebSocketRequestEvents.POD_SET_GOAL,
      handler: handlePodSetGoal,
      schema: podSetGoalSchema,
      responseEvent: WebSocketResponseEvents.POD_GOAL_SET,
    },
    {
      event: WebSocketRequestEvents.POD_SET_PROVIDER,
      handler: handlePodSetProvider,
      schema: podSetProviderSchema,
      responseEvent: WebSocketResponseEvents.POD_PROVIDER_SET,
    },
    {
      event: WebSocketRequestEvents.POD_SET_MODEL,
      handler: handlePodSetModel,
      schema: podSetModelSchema,
      responseEvent: WebSocketResponseEvents.POD_MODEL_SET,
    },
    {
      event: WebSocketRequestEvents.POD_SET_THINKING_LEVEL,
      handler: handlePodSetThinkingLevel,
      schema: podSetThinkingLevelSchema,
      responseEvent: WebSocketResponseEvents.POD_THINKING_LEVEL_SET,
    },
    {
      event: WebSocketRequestEvents.POD_SET_FAST_MODE,
      handler: handlePodSetFastMode,
      schema: podSetFastModeSchema,
      responseEvent: WebSocketResponseEvents.POD_FAST_MODE_SET,
    },
    {
      event: WebSocketRequestEvents.POD_SET_SCHEDULE,
      handler: handlePodSetSchedule,
      schema: podSetScheduleSchema,
      responseEvent: WebSocketResponseEvents.POD_SCHEDULE_SET,
    },
    {
      event: WebSocketRequestEvents.POD_SET_MEMORY_ENABLED,
      handler: handlePodSetMemoryEnabled,
      schema: podSetMemoryEnabledSchema,
      responseEvent: WebSocketResponseEvents.POD_MEMORY_ENABLED_SET,
    },
    {
      event: WebSocketRequestEvents.POD_GET_MEMORY,
      handler: handlePodGetMemory,
      schema: podGetMemorySchema,
      responseEvent: WebSocketResponseEvents.POD_MEMORY_RESULT,
    },
    {
      event: WebSocketRequestEvents.POD_CLEAR_MEMORY,
      handler: handlePodClearMemory,
      schema: podClearMemorySchema,
      responseEvent: WebSocketResponseEvents.POD_MEMORY_CLEARED,
    },
    {
      event: WebSocketRequestEvents.POD_DELETE,
      handler: handlePodDelete,
      schema: podDeleteSchema,
      responseEvent: WebSocketResponseEvents.POD_DELETED,
    },
    {
      event: WebSocketRequestEvents.POD_SET_PLUGINS,
      handler: handlePodSetPlugins,
      schema: podSetPluginsSchema,
      responseEvent: WebSocketResponseEvents.POD_PLUGINS_SET,
    },
  ],
});
